server:
  http_listen_port: 9009

distributor:
  ring:
    kvstore:
      store: inmemory

ingester:
  wal:
    enabled: false
  lifecycler:
    ring:
      kvstore:
        store: inmemory

blocks_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir-data