{
 "title": "Flask App",
 "templating": {
  "list": [
   { "name": "DS_LOKI", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Live Logs",
   "type": "logs",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "{job=\"flask\"}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate({job=\"flask\"}[1m])"
    }
   ]
  },
  {
   "title": "Error Count (1h)",
   "type": "stat",
   "gridPos": { "x": 12, "y": 8, "w": 6, "h": 8 },
   "targets": [
    {
     "expr": "count_over_time({job=\"flask\"} |= \"ERROR\" [1h])"
    }
   ]
  },
  {
   "title": "Nginx Logs",
   "type": "logs",
   "gridPos": { "x": 0, "y": 16, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "{job=\"nginx\"}"
    }
   ]
  }
 ]
}