name: Terraform Plan and Validate

on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/infra/**'

permissions:
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan and Validate
    runs-on: ubuntu-latest
    timeout-minutes: 15
    # A newer push to the same PR makes the older plan obsolete.
    concurrency:
      group: terraform-plan-frontend-${{ github.ref }}
      cancel-in-progress: true
    defaults:
      run:
        working-directory: frontend/infra
    steps:
      - name: Checkout repo
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        
      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

        # this requires TF_API_TOKEN to be set in the repo secrets = Team Token (generated in Terraform Workspaces -> Settings -> API Tokens)
      - name: Terraform Plan
        run: terraform plan 